apiVersion: v1
entries:
  stuf:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-21T11:36:19.2266621Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 210f1da2e480cd34631b3cb1cc5b472712cef8ef9abdf47242519ad5ea2be4d5
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: stuf
    urls:
    - stuf-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-21T11:36:19.222005Z"
